# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    cache:
        psr6_app_cache:
            psr6:
                service: cache.flysystem.psr6

    adapters:
        public_uploads_adapter:
#            local:
#                directory: '%kernel.project_dir%/public/%uploads_dir_name%'
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_ACCESS_BUCKET)%'

#        private_uploads_adapter:
##            local:
##                directory: '%kernel.project_dir%/var/uploads'
#            awss3v3:
#                client: Aws\S3\S3Client
#                bucket: '%env(AWS_S3_ACCESS_BUCKET)%'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
# Injected as a Service
#            alias: League\Flysystem\Filesystem
#        private_uploads_filesystem:
#            adapter: private_uploads_adapter
        cached_public_uploads_filesystem:
            adapter: public_uploads_adapter
            cache: psr6_app_cache
